baseURL = "https://manxisuo.github.io/"
languageCode = "zh-cn"
title = "Manxisuo的博客"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "博文"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 30
